name: 'Install'
description: 'Install and pre-build'

runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        node-version: 20.x

    - name: Install Dependencies
      shell: bash
      run: yarn install
